# Generated by Django 2.2 on 2019-05-14 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='pessoa_data_nascimento',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 15, 30, 4, 971732), verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoamodel',
            name='pessoa_numero',
            field=models.CharField(max_length=5, verbose_name='Numero'),
        ),
    ]
