# Generated by Django 2.2 on 2019-05-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20190514_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoModel',
            fields=[
                ('contato_id', models.AutoField(primary_key=True, serialize=False)),
                ('contato_telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.PessoaModel')),
            ],
        ),
    ]
