# Generated by Django 2.2 on 2019-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nome', models.CharField(max_length=100, verbose_name='Estado_Nome')),
                ('estado_sigla', models.CharField(max_length=2, verbose_name='Estado_Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['estado_nome'],
            },
        ),
    ]
